config/routes.rb
Rails.application.routes.draw do

  resources :libraries do
    collection { post :import_csv}
  end
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        :invitations => 'users/invitations'
      }


  root to: 'libraries#index'

  # devise_for :users
  class ApiConstraints
    def initialize(options)
      @version = options[:version]
      @default = options[:default]
      
    end

    def matches?(req)
      # binding.pry
      @default || req.headers['Accept'].include?("application/v#{@version}")
    end
  end

      


  namespace :api do
      devise_for :users, :controllers => { registrations: 'api/registrations' }
    scope module: :v2, format: :json, constraints: ApiConstraints.new(version: 2) do
        # devise_for :users, :controllers => { registrations: 'api/registrations' }
        devise_scope :user do
          post 'sign_up', to: 'registrations'
          post 'sign_in', to: 'registrations', defaults: {format: :json}
          post 'logout', to: 'registrations', defaults: {format: :json}
          post 'invite_user', to: 'registrations', defaults: {format: :json}

        end
      post 'libraries/purchase'
      resources :libraries, defaults: {format: :json}

    end
  # end

  # namespace :api do
    scope module: :v1, format: :json, constraints: ApiConstraints.new(version: 1, default: true) do

      # devise_for :users, :controllers => { registrations: 'api/registrations' }
     

      devise_scope :user do
        post 'sign_up', to: 'registrations', defaults: {format: :json}
        post 'sign_in', to: 'registrations', defaults: {format: :json}
        post 'logout', to: 'registrations', defaults: {format: :json}       


      end
      post 'libraries/purchase'
      resources :libraries, defaults: {format: :json}
    end
  end  
end

app/models/library.rb
class Library < ActiveRecord::Base
	require 'csv'

	belongs_to :admin, foreign_key: "created_by"
	belongs_to :normal, foreign_key: "created_by"
	belongs_to :user, foreign_key: "created_by"

	validates_uniqueness_of :ref_id

	before_create do
		self.ref_id = SecureRandom.hex if self.ref_id.nil?		
	end



	def self.import(file)

		# a = File.open("#{Rails.root}/test.csv")
		# b = File.open("#{ENV['HOME']}/Desktop/test.csv")
		# Rails.root.join('test.csv')

		# a = [[1123,nil,1,'asdfasdfasdfsdfasdf'],[1123,nil,1,'asdfasdfasdfsdfasdf']]
		CSV.foreach(file.path, headers: true) do |row|
		# a.each do |row|
			# binding.pry
			library = Library.new
			library.ref_id = row[0]
			library.purchased_on = Date.today 
			library.in_possession_of = row[2] 
			library.description = row[3]
			
			if library.save
			
			else
				@errors = [ ]
				library.errors.full_messages.each do |row,message|
					@errors << "#{message} at #{row}"
				end
			end 
			
			@errors #  <- need to return the @errors array 
		end
		# binding.pry
		puts @errors.blank? ? 'Success' : @errors
	end


end


# a || a = b



# a=1, b=3
# a=nil, b='n'
# a=true b=false
# a=false, b=true
# a=false, b=1

app/controllers/api/v1/libraries_controller.rb
class Api::V1::LibrariesController < ApiController
	before_action :check_for_valid_authtoken
	before_action :set_library, only: [:show, :edit, :update, :destroy, :purchase]
	skip_before_action :verify_authenticity_token
	after_action  :verify_authorized

	def index
		@libraries = Library.all
		# binding.pry
		render :status => 400,
		      	:json => {:message => 'all', :library => @libraries}
	end

	def show
		authorize @library
	end

	def new
		@library = Library.new
	end

	def edit
	end

	def create
		@library = Library.new(library_params)
		@library.created_by = @user.id
		
		authorize @library
		# LibraryPolicy.new(@user, @library).create?

		if @library.save
			render :status => 400,
		      	:json => {:message => 'created', :library => @library}
		else
			render :status => 400,
	      	:json => {:message => @library.errors.full_messages}
		end
	end

	def update
		authorize @library
		if @library.update(library_params)
		render :status => 400,
	      	:json => {:message => 'updated', :library => @library}
		else
			render :status => 400,
	      	:json => {:message => 'not updated'}
		end
	end

	def destroy
		@library.destroy
		render :status => 400,
	      	:json => {:message => 'updated', :library => @library}
	end

	def purchase
		@library.update_attributes(:purchased_on => Date.today, :in_possession_of => @library.user.id)
		render :status => 400, :json => {:message => 'Purchased', :library => @library}
	end

	private
	def set_library
		@library = Library.find(params[:id])
	end

	# Never trust parameters from the scary internet, only allow the white list through.
	def library_params
		# params.permit(:name)
		params.permit(:name, :created_by)
	end
end

app/controllers/api/v2/libraries_controller.rb
class Api::V2::LibrariesController < ApiController
	before_action :check_for_valid_authtoken
	before_action :set_library, only: [:show, :edit, :update, :destroy, :purchase]
	skip_before_action :verify_authenticity_token
	after_action :verify_authorized, except: :index

	def index
		@libraries = Library.all
		# binding.pry
		render :status => 400,
		      	:json => {:message => 'all', :library => @libraries}
	end

	def show
	end

	def new
		@library = Library.new
	end

	def edit
	end

	def create
		authorize Library
		@library = Library.new(library_params)
		@library.created_by = @user.id

		# authorize @library
		# LibraryPolicy.new(@user, @library).create?
		if @library.save
			render :status => 400,
		      	:json => {:message => 'created', :library => @library}
		else
			render :status => 400,
	      	:json => {:message => @library.errors.full_messages}
		end
	end

	def update
		
		if @library.update(library_params)
		render :status => 400,
	      	:json => {:message => 'updated', :library => @library}
		else
			render :status => 400,
	      	:json => {:message => 'not updated'}
		end
	end

	def destroy
		@library.destroy
		render :status => 400,
	      	:json => {:message => 'updated', :library => @library}
	end

	def purchase
		@library.update_attributes(:purchased_on => Date.today, :in_possession_of => @library.user.id)
		render :status => 400, :json => {:message => 'Purchased', :library => @library}
	end

	private
	def set_library
		@library = Library.find(params[:id])
	end

	# Never trust parameters from the scary internet, only allow the white list through.
	def library_params
		# binding.pry
		params.permit(:name, :description, :title, :created_by)
	end
end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController
  before_action :set_library, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    if params[:file]
      Library.import(params[:file])
      redirect_to root_url
    else
      @libraries = Library.all
    end
  end

  def show
  end

  def new
    @library = Library.new
  end

  def edit
  end

  def create
    @library = Library.new(library_params)
    # binding.pry
    @library.created_by = current_user.id
    respond_to do |format|
      if @library.save
        format.html { redirect_to @library, notice: 'Library was successfully created.' }
        format.json { render :show, status: :created, location: @library }
      else
        format.html { render :new }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @library.update(library_params)
        format.html { redirect_to @library, notice: 'Library was successfully updated.' }
        format.json { render :show, status: :ok, location: @library }
      else
        format.html { render :edit }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @library.destroy
    respond_to do |format|
      format.html { redirect_to libraries_url, notice: 'Library was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import_csv
      current_user.libraries.import(params[:file])
      redirect_to root_url
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_library
      @library = Library.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def library_params
      params.require(:library).permit(:name, :description, :created_by)
    end
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/views/libraries/_form.html.erb
<%= form_for(@library) do |f| %>
  <% if @library.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@library.errors.count, "error") %> prohibited this library from being saved:</h2>

      <ul>
      <% @library.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :created_by %><br>
    <%= f.number_field :created_by %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/libraries/edit.html.erb
<h1>Editing Library</h1>

<%= render 'form' %>

<%= link_to 'Show', @library %> |
<%= link_to 'Back', libraries_path %>

app/views/libraries/index.html.erb
Override devise sign in should accept user name
Convert standard rails logging into a JSON log. 
v1 library record creation


<p id="notice"><%= notice %></p>
<%= current_user.email %>
<h1>Listing Libraries</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Created by</th>
      <th>Ref</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @libraries.each do |library| %>
      <tr>
        <td><%= library.name %></td>
        <td><%= library.description %></td>
        <td><%= library.created_by %></td>
        <td><%= library.ref_id %></td>
        <td><%= link_to 'Show', library %></td>
        <td><%= link_to 'Edit', edit_library_path(library) %></td>
        <td><%= link_to 'Destroy', library, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Library', new_library_path %>


<% if @errors %>
  <% @errors.each do |message| %>
    <%= message %>
  <% end %>
<% end %>



<%= form_tag import_csv_libraries_path, :multipart => true do %>

  <%= file_field_tag :file %>
  <% hidden_field_tag :user_id => current_user.id %>
  <%= submit_tag 'submit'%>
<% end %>

app/views/libraries/new.html.erb
<h1>New Library</h1>

<%= render 'form' %>

<%= link_to 'Back', libraries_path %>

app/views/libraries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @library.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @library.description %>
</p>

<p>
  <strong>Created by:</strong>
  <%= @library.created_by %>
</p>

<%= link_to 'Edit', edit_library_path(@library) %> |
<%= link_to 'Back', libraries_path %>